/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * MTG Label Generator
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response model for an MTG set.
 */
export interface MTGSetResponse {
  id: string;
  name: string;
  code: string;
  set_type: string;
  card_count?: number;
  released_at?: string | null;
  icon_svg_uri?: string | null;
  scryfall_uri?: string | null;
}
